### ISSUE TITLE
Able to send from form, but not receiving anything in specified email.

### ISSUE THREAD

**Issue by karl-x** [JDutil/contact_us#63]
Hi There!

Firstly thanks for the form. I have followed the instructions in your Reamdme but cant seem to receive the email. 

I have already amended the `config.mailer_to`, cant seem to find out what's wrong. Any suggestions on where i should be looking?

THANKS!
Karl

**Comment by JDutil** [comment]
@karl-x it sounds like you need to configure your rails application's mail settings.  This extension assumes that's already been done for your application because everyone's settings are different.

Here's the Rails guides on it, but you may want to check with your hosting provider for something more specific:
http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
http://guides.rubyonrails.org/configuring.html#configuring-action-mailer
